name: Build Docker Image

on:
  workflow_call:
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: ghcr.io/Snipy7374/code-jam-24-universes
        tags: type=ref,event=branch
    - name: Login to GHCR
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - uses: docker/setup-qemu-action@v2
    - uses: docker/setup-buildx-action@v2
    - name: Build container
      uses: docker/build-push-action@v4
      with:
        context: .
        file: .docker/Dockerfile
        platforms: linux/amd64,linux/arm64
        push: true
        tags: ${{ steps.meta.outputs.tags }}
